url: http://ablwr.github.io
title: BLOG Progress Process
subtitle: Amateur hacking.
author: 
  name: Ashley Blewer
  url: http://www.ashleyblewer.com
simple_search: https://www.google.com/search
description:

markdown: kramdown
highlighter: rouge
date_format: "ordinal"
baseurl: /
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories

gems: [jekyll-paginate, jekyll-feed]
paginate: 15

titlecase: true

github_user: ablwr

twitter_user: ablwr
twitter_tweet_button: true
